name: 'Container Build Flow Action'
description: 'Automated Docker/Container builds with PR/WIP/DEV/PATCH flow support for Docker Hub and GitHub Container Registry'
author: 'WG Technology Labs'

branding:
  icon: 'package'
  color: 'blue'

inputs:
  # Registry Configuration
  registry:
    description: 'Target container registry (docker-hub, ghcr, or both)'
    required: false
    default: 'both'
  
  # Docker Hub Credentials
  dockerhub-username:
    description: 'Docker Hub username (required if registry includes docker-hub)'
    required: false
    default: ''
  
  dockerhub-token:
    description: 'Docker Hub access token (required if registry includes docker-hub)'
    required: false
    default: ''
  
  dockerhub-username-secret:
    description: 'Name of secret containing Docker Hub username'
    required: false
    default: 'DOCKERHUB_USERNAME'
  
  dockerhub-token-secret:
    description: 'Name of secret containing Docker Hub token'
    required: false
    default: 'DOCKERHUB_TOKEN'
  
  # GitHub Container Registry Credentials
  ghcr-token:
    description: 'GitHub token for GHCR (defaults to GITHUB_TOKEN)'
    required: false
    default: ''
  
  ghcr-username:
    description: 'GitHub username for GHCR (defaults to repository owner)'
    required: false
    default: ''
  
  # Branch Configuration
  main-branch:
    description: 'Name of the main/production branch'
    required: false
    default: 'main'
  
  dev-branch:
    description: 'Name of the development branch'
    required: false
    default: 'dev'
  
  # Build Configuration
  dockerfile:
    description: 'Path to Dockerfile'
    required: false
    default: './Dockerfile'
  
  context:
    description: 'Build context path'
    required: false
    default: '.'
  
  platforms:
    description: 'Target platforms (comma-separated, e.g., linux/amd64,linux/arm64)'
    required: false
    default: 'linux/amd64'
  
  build-args:
    description: 'Build arguments (newline-separated, e.g., ARG1=value1)'
    required: false
    default: ''
  
  labels:
    description: 'Image labels (newline-separated, e.g., key=value)'
    required: false
    default: ''
  
  cache-enabled:
    description: 'Enable build cache'
    required: false
    default: 'true'
  
  # Image Naming
  image-name:
    description: 'Container image name (defaults to repository name)'
    required: false
    default: ''
  
  tag-prefix:
    description: 'Prefix for image tags (e.g., v1-)'
    required: false
    default: ''
  
  tag-suffix:
    description: 'Suffix for image tags (e.g., -alpine)'
    required: false
    default: ''
  
  # PR Comment Configuration
  pr-comment-enabled:
    description: 'Enable PR comments with pull instructions'
    required: false
    default: 'true'
  
  pr-comment-template:
    description: 'Custom PR comment template (supports variables: {BUILD_FLOW}, {IMAGE_TAGS}, {REGISTRY_URLS})'
    required: false
    default: ''
  
  # Advanced Options
  push-enabled:
    description: 'Enable pushing to registry (set to false for testing)'
    required: false
    default: 'true'
  
  load-enabled:
    description: 'Load image to Docker daemon (useful for local testing)'
    required: false
    default: 'false'
  
  provenance:
    description: 'Enable provenance attestation'
    required: false
    default: 'true'
  
  sbom:
    description: 'Enable SBOM attestation'
    required: false
    default: 'true'
  
  # Security Scanning Configuration
  pre-build-scan-enabled:
    description: 'Enable pre-build security scanning (source code + Dockerfile)'
    required: false
    default: 'true'
  
  scan-source-code:
    description: 'Scan source code and dependencies before building'
    required: false
    default: 'true'
  
  scan-dockerfile:
    description: 'Scan Dockerfile for misconfigurations and best practices'
    required: false
    default: 'true'
  
  image-scan-enabled:
    description: 'Enable post-build container image scanning'
    required: false
    default: 'true'
  
  trivy-severity:
    description: 'Trivy severity levels to scan (comma-separated: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL)'
    required: false
    default: 'HIGH,CRITICAL'
  
  trivy-ignore-unfixed:
    description: 'Ignore vulnerabilities without available fixes'
    required: false
    default: 'false'
  
  trivy-timeout:
    description: 'Trivy scan timeout duration (e.g., 5m0s, 10m0s)'
    required: false
    default: '10m0s'
  
  trivy-skip-dirs:
    description: 'Directories to skip during Trivy scan (comma-separated)'
    required: false
    default: ''
  
  trivy-skip-files:
    description: 'Files to skip during Trivy scan (comma-separated)'
    required: false
    default: ''
  
  upload-sarif:
    description: 'Upload vulnerability scan results to GitHub Security tab (SARIF format)'
    required: false
    default: 'true'
  
  sarif-category-source:
    description: 'SARIF category name for source code scan'
    required: false
    default: 'trivy-source-scan'
  
  sarif-category-dockerfile:
    description: 'SARIF category name for Dockerfile scan'
    required: false
    default: 'trivy-dockerfile-scan'
  
  sarif-category-image:
    description: 'SARIF category name for container image scan'
    required: false
    default: 'trivy-container-scan'
  
  vulnerability-comment-enabled:
    description: 'Add comprehensive vulnerability scan results to PR comments'
    required: false
    default: 'true'
  
  enable-image-comparison:
    description: 'Compare vulnerabilities with baseline image'
    required: false
    default: 'false'
  
  comparison-baseline-image:
    description: 'Baseline image tag to compare against (e.g., myapp:latest)'
    required: false
    default: ''
  
  fail-on-vulnerability:
    description: 'Fail the build if vulnerabilities are found at or above trivy-severity level'
    required: false
    default: 'false'

outputs:
  image-tags:
    description: 'Complete list of applied image tags'
    value: ${{ steps.output.outputs.image-tags }}
  
  registry-urls:
    description: 'Full image URLs for each registry'
    value: ${{ steps.output.outputs.registry-urls }}
  
  build-digest:
    description: 'SHA256 digest of the built image'
    value: ${{ steps.output.outputs.build-digest }}
  
  build-flow-type:
    description: 'Detected build flow type (pr, dev, patch, staging, wip)'
    value: ${{ steps.output.outputs.build-flow-type }}
  
  short-sha:
    description: 'Short commit SHA used in tags'
    value: ${{ steps.output.outputs.short-sha }}
  
  # Security Scanning Outputs
  vulnerability-scan-completed:
    description: 'Whether vulnerability scanning completed successfully (true/false)'
    value: ${{ steps.scan-summary.outputs.completed }}
  
  total-vulnerabilities:
    description: 'Total number of vulnerabilities found'
    value: ${{ steps.scan-summary.outputs.total }}
  
  critical-vulnerabilities:
    description: 'Number of CRITICAL severity vulnerabilities'
    value: ${{ steps.scan-summary.outputs.critical }}
  
  high-vulnerabilities:
    description: 'Number of HIGH severity vulnerabilities'
    value: ${{ steps.scan-summary.outputs.high }}
  
  medium-vulnerabilities:
    description: 'Number of MEDIUM severity vulnerabilities'
    value: ${{ steps.scan-summary.outputs.medium }}
  
  low-vulnerabilities:
    description: 'Number of LOW severity vulnerabilities'
    value: ${{ steps.scan-summary.outputs.low }}

runs:
  using: 'composite'
  steps:
    - name: Resolve Commit SHA
      id: sha
      shell: bash
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ] || [ "${{ github.event_name }}" = "pull_request_target" ]; then
          echo "sha=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
        else
          echo "sha=${{ github.sha }}" >> $GITHUB_OUTPUT
        fi
    
    - name: Detect Build Flow and Generate Tags
      id: detect
      shell: bash
      run: |
        bash ${{ github.action_path }}/scripts/detect-build-flow.sh
      env:
        GITHUB_SHA: ${{ steps.sha.outputs.sha }}
        MAIN_BRANCH: ${{ inputs.main-branch }}
        DEV_BRANCH: ${{ inputs.dev-branch }}
        TAG_PREFIX: ${{ inputs.tag-prefix }}
        TAG_SUFFIX: ${{ inputs.tag-suffix }}
        IMAGE_NAME: ${{ inputs.image-name }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    # =============================================================================
    # PRE-BUILD SECURITY SCANNING
    # =============================================================================
    
    - name: Run Trivy Filesystem Scan (Source Code)
      if: inputs.pre-build-scan-enabled == 'true' && inputs.scan-source-code == 'true'
      uses: aquasecurity/trivy-action@0.28.0
      continue-on-error: true
      with:
        scan-type: 'fs'
        scan-ref: ${{ inputs.context }}
        format: 'json'
        output: 'trivy-source-results.json'
        severity: ${{ inputs.trivy-severity }}
        ignore-unfixed: ${{ inputs.trivy-ignore-unfixed }}
        timeout: ${{ inputs.trivy-timeout }}
        skip-dirs: ${{ inputs.trivy-skip-dirs }}
        skip-files: ${{ inputs.trivy-skip-files }}
    
    - name: Upload Source Code Scan to GitHub Security
      if: inputs.pre-build-scan-enabled == 'true' && inputs.scan-source-code == 'true' && inputs.upload-sarif == 'true'
      uses: aquasecurity/trivy-action@0.28.0
      continue-on-error: true
      with:
        scan-type: 'fs'
        scan-ref: ${{ inputs.context }}
        format: 'sarif'
        output: 'trivy-source-results.sarif'
        severity: ${{ inputs.trivy-severity }}
        ignore-unfixed: ${{ inputs.trivy-ignore-unfixed }}
        timeout: ${{ inputs.trivy-timeout }}
        skip-dirs: ${{ inputs.trivy-skip-dirs }}
        skip-files: ${{ inputs.trivy-skip-files }}
    
    - name: Upload Source Scan SARIF
      if: inputs.pre-build-scan-enabled == 'true' && inputs.scan-source-code == 'true' && inputs.upload-sarif == 'true'
      uses: github/codeql-action/upload-sarif@v3
      continue-on-error: true
      with:
        sarif_file: 'trivy-source-results.sarif'
        category: ${{ inputs.sarif-category-source }}
    
    - name: Run Trivy Config Scan (Dockerfile)
      if: inputs.pre-build-scan-enabled == 'true' && inputs.scan-dockerfile == 'true'
      uses: aquasecurity/trivy-action@0.28.0
      continue-on-error: true
      with:
        scan-type: 'config'
        scan-ref: ${{ inputs.dockerfile }}
        format: 'json'
        output: 'trivy-dockerfile-results.json'
        severity: ${{ inputs.trivy-severity }}
        timeout: ${{ inputs.trivy-timeout }}
    
    - name: Upload Dockerfile Scan to GitHub Security
      if: inputs.pre-build-scan-enabled == 'true' && inputs.scan-dockerfile == 'true' && inputs.upload-sarif == 'true'
      uses: aquasecurity/trivy-action@0.28.0
      continue-on-error: true
      with:
        scan-type: 'config'
        scan-ref: ${{ inputs.dockerfile }}
        format: 'sarif'
        output: 'trivy-dockerfile-results.sarif'
        severity: ${{ inputs.trivy-severity }}
        timeout: ${{ inputs.trivy-timeout }}
    
    - name: Upload Dockerfile Scan SARIF
      if: inputs.pre-build-scan-enabled == 'true' && inputs.scan-dockerfile == 'true' && inputs.upload-sarif == 'true'
      uses: github/codeql-action/upload-sarif@v3
      continue-on-error: true
      with:
        sarif_file: 'trivy-dockerfile-results.sarif'
        category: ${{ inputs.sarif-category-dockerfile }}
    
    # =============================================================================
    # BUILD STAGE
    # =============================================================================
    
    - name: Login to Docker Hub
      if: inputs.registry == 'docker-hub' || inputs.registry == 'both'
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}
    
    - name: Login to GitHub Container Registry
      if: inputs.registry == 'ghcr' || inputs.registry == 'both'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.ghcr-username || github.repository_owner }}
        password: ${{ inputs.ghcr-token || github.token }}
    
    - name: Extract Docker Metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ (inputs.registry == 'docker-hub' || inputs.registry == 'both') && steps.detect.outputs.dockerhub-image || '' }}
          ${{ (inputs.registry == 'ghcr' || inputs.registry == 'both') && steps.detect.outputs.ghcr-image || '' }}
        tags: |
          type=raw,value=${{ steps.detect.outputs.tags }}
        labels: |
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          org.opencontainers.image.revision=${{ steps.sha.outputs.sha }}
          org.opencontainers.image.created=${{ github.event.repository.updated_at }}
          ${{ inputs.labels }}
    
    - name: Build and Push Container Image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push-enabled }}
        load: ${{ inputs.load-enabled }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: ${{ inputs.build-args }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        provenance: ${{ inputs.provenance }}
        sbom: ${{ inputs.sbom }}
    
    - name: Generate Action Outputs
      id: output
      shell: bash
      run: |
        bash ${{ github.action_path }}/scripts/generate-outputs.sh
      env:
        BUILD_DIGEST: ${{ steps.build.outputs.digest }}
        BUILD_METADATA: ${{ steps.build.outputs.metadata }}
        BUILD_FLOW_TYPE: ${{ steps.detect.outputs.build-flow-type }}
        IMAGE_TAGS: ${{ steps.meta.outputs.tags }}
        SHORT_SHA: ${{ steps.detect.outputs.short-sha }}
        REGISTRY: ${{ inputs.registry }}
    
    # =============================================================================
    # POST-BUILD SECURITY SCANNING
    # =============================================================================
    
    - name: Scan Baseline Image (for comparison)
      if: inputs.image-scan-enabled == 'true' && inputs.enable-image-comparison == 'true' && inputs.comparison-baseline-image != ''
      uses: aquasecurity/trivy-action@0.28.0
      continue-on-error: true
      with:
        scan-type: 'image'
        image-ref: ${{ inputs.comparison-baseline-image }}
        format: 'json'
        output: 'trivy-baseline-results.json'
        severity: ${{ inputs.trivy-severity }}
        ignore-unfixed: ${{ inputs.trivy-ignore-unfixed }}
        timeout: ${{ inputs.trivy-timeout }}
    
    - name: Scan Container Image
      if: inputs.image-scan-enabled == 'true'
      uses: aquasecurity/trivy-action@0.28.0
      continue-on-error: true
      with:
        scan-type: 'image'
        image-ref: ${{ steps.meta.outputs.tags }}
        format: 'json'
        output: 'trivy-image-results.json'
        severity: ${{ inputs.trivy-severity }}
        ignore-unfixed: ${{ inputs.trivy-ignore-unfixed }}
        timeout: ${{ inputs.trivy-timeout }}
    
    - name: Parse Trivy Results and Generate Summary
      if: inputs.image-scan-enabled == 'true'
      id: scan-summary
      shell: bash
      run: |
        node ${{ github.action_path }}/scripts/parse-trivy-results.js
    
    - name: Generate Vulnerability Comparison
      if: inputs.image-scan-enabled == 'true' && inputs.enable-image-comparison == 'true'
      shell: bash
      continue-on-error: true
      run: |
        node ${{ github.action_path }}/scripts/generate-comparison.js
    
    - name: Check Vulnerability Threshold
      if: inputs.image-scan-enabled == 'true' && inputs.fail-on-vulnerability == 'true'
      shell: bash
      run: |
        if [ -f trivy-scan-summary.json ]; then
          CRITICAL=$(jq -r '.critical // 0' trivy-scan-summary.json)
          HIGH=$(jq -r '.high // 0' trivy-scan-summary.json)
          
          echo "Critical vulnerabilities: $CRITICAL"
          echo "High vulnerabilities: $HIGH"
          
          if [[ "${{ inputs.trivy-severity }}" == *"CRITICAL"* ]] && [ "$CRITICAL" -gt 0 ]; then
            echo "❌ Build failed: $CRITICAL CRITICAL vulnerabilities found"
            exit 1
          fi
          
          if [[ "${{ inputs.trivy-severity }}" == *"HIGH"* ]] && [ "$HIGH" -gt 0 ]; then
            echo "❌ Build failed: $HIGH HIGH vulnerabilities found"
            exit 1
          fi
          
          echo "✅ No vulnerabilities above threshold found"
        else
          echo "⚠️ Scan summary not found, skipping threshold check"
        fi
    
    - name: Upload Container Image Scan to GitHub Security
      if: inputs.image-scan-enabled == 'true' && inputs.upload-sarif == 'true'
      uses: aquasecurity/trivy-action@0.28.0
      continue-on-error: true
      with:
        scan-type: 'image'
        image-ref: ${{ steps.meta.outputs.tags }}
        format: 'sarif'
        output: 'trivy-image-results.sarif'
        severity: ${{ inputs.trivy-severity }}
        ignore-unfixed: ${{ inputs.trivy-ignore-unfixed }}
        timeout: ${{ inputs.trivy-timeout }}
    
    - name: Upload Image Scan SARIF
      if: inputs.image-scan-enabled == 'true' && inputs.upload-sarif == 'true'
      uses: github/codeql-action/upload-sarif@v3
      continue-on-error: true
      with:
        sarif_file: 'trivy-image-results.sarif'
        category: ${{ inputs.sarif-category-image }}
    
    # =============================================================================
    # PR COMMENT WITH SECURITY RESULTS
    # =============================================================================
    
    - name: Comment on Pull Request
      if: inputs.pr-comment-enabled == 'true'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.ghcr-token || github.token }}
        script: |
          const fs = require('fs');
          const scriptPath = '${{ github.action_path }}/scripts/pr-comment.js';
          const script = require(scriptPath);
          await script({github, context, core});
      env:
        BUILD_FLOW_TYPE: ${{ steps.detect.outputs.build-flow-type }}
        IMAGE_TAGS: ${{ steps.output.outputs.image-tags }}
        REGISTRY_URLS: ${{ steps.output.outputs.registry-urls }}
        PR_COMMENT_TEMPLATE: ${{ inputs.pr-comment-template }}
        REGISTRY: ${{ inputs.registry }}
        RESOLVED_SHA: ${{ steps.sha.outputs.sha }}
        VULNERABILITY_COMMENT_ENABLED: ${{ inputs.vulnerability-comment-enabled }}
        PRE_BUILD_SCAN_ENABLED: ${{ inputs.pre-build-scan-enabled }}
        IMAGE_SCAN_ENABLED: ${{ inputs.image-scan-enabled }}
        ENABLE_IMAGE_COMPARISON: ${{ inputs.enable-image-comparison }}
